---
- name: Setup instance and Launch Docker container
  hosts: test
  become: yes

  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        upgrade: dist

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      ignore_errors: yes  
      with_items:
        - ca-certificates
        - curl
        - gnupg

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    
    - name: Install Python3 and pip
      ansible.builtin.apt:
        name: "{{ item}}"
        state: present
      with_items:
        - python3
        - python3-pip

    - name: Install Docker module for Python
      pip:
        name: docker

    - name: Launch Docker container
      community.docker.docker_container:
        name: test
        image: httpd
        state: started
        restart_policy: "unless-stopped"

    - name: Change hostname on Docker container
      community.docker.docker_container_exec:
        container: test
        command: /bin/bash -c "echo Hello World! > /usr/local/apache2/htdocs/index.html"
  

# Maintenances
