---
- name: Open port 80
  hosts: all
  become: yes

  tasks:
  - name: Set firewall rule
    shell: firewall-cmd --zone=public --add-port=80/tcp --permanent

  - name: Restart firewall rule
    shell: firewall-cmd --reload