---
- name: Open HTTP and HTTPS ports
  hosts: test
  become: yes

  tasks: 
    - name: Install firewalld
      apt:
        name: firewalld
        state: present

    - name: Open HTTP and HTTPS ports
      ansible.posix.firewalld: 
       port: "{{ item }}"
       state: enabled
      with_items: 
       - 80/tcp
       - 443/tcp
