---
- name: nothing
  hosts: localhost
  gather_facts: false

  tasks:
    # - name: Install pre-requisites
    #   become: yes
    #   pip:
    #     name: 
    #       - openshift
    #       - pyyaml
    #       - kubernetes

    - name: Create k8s namespace
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        name: testing
        api_version: v1
        kind: Namespace
        state: present

    - name: test
      kubernetes.core.k8s:
        state: present
        src: "./k8s/{{ item }}"
      with_items:
        - deployment.yaml
        - daemonset.yaml
        - services.yaml