---
- name: 
  hosts: all
  become: yes

  vars:
    mytext: "Ansible"
    password: "Passw0rd"

  tasks:
    - name: Ping test
      ping:

    - name: Unregister Server from Load Balancer
      shell: echo This Server {{ inventory_hostname }} was deregistered from Load Balancer, Node name is {{ ansible_nodename }} >> /home/log.txt
      delegate_to: 127.0.0.1

    - name: Create file1
      copy:
        dest: /home/file1.txt
        content: |
          Some information
          Some word: {{ mytext }}

    - name: Create file1
      copy:
        dest: /home/file2.txt
        content: |
          Some information
          Password: {{ password }}
      delegate_to: target3

    - name: Reboot my servers
      shell: sleep 5 && reboot now
      async: 1
      poll: 0
    
    - name: Wait till my servers is up
      wait_for:
        host: targets
        state: started
        delay: 5 
        timeout: 40 # Maximum wait time
      delegate_to: 127.0.0.1
