---
- name: Launch and change hostname on Docker container
  hosts: test
  become: yes

  tasks:
    - name: Launch Docker container
      docker_container:
        name: test
        image: ubuntu
        state: started

    - name: Change hostname on Docker container
      docker_container_exec:
        command: echo target > /etc/hostname