---
- name: Launch and change hostname on Docker container
  hosts: test
  become: yes

  tasks:
    - name: Install Docker
      ansible.builtin.yum:
        name: "{{ item }}"
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Launch Docker container
      community.docker.docker_container:
        name: test
        image: ubuntu
        state: started

    - name: Change hostname on Docker container
      community.docker.docker_container_exec:
        container: test
        command: /bin/bash -c "echo target > /etc/hostname"
  

# Maintenances