---
- name: Launch and change hostname on Docker container
  hosts: test
  become: yes

  tasks:
    - name: Launch Docker container
      docker_container:
        name: test
        image: ubuntu
        state: started

    # - name: Change hostname on Docker container
    #   community.docker.docker_container_exec:
    #     container: test
    #     command: /bin/bash -c "echo target > /etc/hostname"
    #     chdir: /root
    - name: Run a simple command (command)
      community.docker.docker_container_exec:
        container: test
        command: /bin/bash -c "echo target > /etc/hostname"
  

# Maintenances  