---
- name: Handling errors
  hosts: all
  become: yes

  tasks:
    - name: Install package
      yum: name=treeeee state=latest
      ignore_errors: yes


    - name: Get wd path
      shell: ls -la /var/www/html
      register: result
      failed_when: "'log.txt' in result.stdout"

    - name: Print wd path
      debug:
        var: result

    - name: Print Passw0rd
      shell: echo Passw0rd

