---
- name: Open HTTP and HTTPS ports
  hosts: test
  become: yes

  tasks: 
   - name: Open HTTP and HTTPS ports
     ansible.posix.firewalld: 
      port: "{{ item }}"
      protocol: tcp
     with_items: 
      - http
      - https