---
- name: Check uptime on all hosts
  hosts: all
  become: yes

  tasks:
    - name: Get uptime
      shell: uptime
      register: result

    - name: Print uptime
      debug:
        var: result