---
- name:
  hosts: test
  become: yes

  tasks:
    - name: Create user
      ansible:
        name: tempuser
        shell: /bin/bash
        password: "{{ temppass | password_hash('sha512') }}"


