---
- name:
  hosts: test
  become: yes

  vars:
    mypassword: temp

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: tempuser
        shell: /bin/bash
        password: "{{ mypassword | password_hash('sha512') }}"

