---
- name: Install Apache and Upload my Web page
  hosts: all
  become: yes

  vars:
    source_folder: ./page/
    destin_folder: /var/www/html

  tasks:

  - block:  # RedHat Block

    # Install Apache on RedHat
    - name: Install Apache RedHat
      yum: name=httpd state=installed
      when: ansible_os_family == "RedHat"

    # Enable Service RedHat
    - name: Start service and enable Start on boot (RedHat)
      service: name=httpd state=started enabled=yes
      when: ansible_os_family == "RedHat" 

  - block:  # Debian Block

    # Install Apache on Debian
    - name: Install Apache Debian
      apt: name=apache2 state=installed
      when: ansible_os_family == "Debian"

    # Enable Service Debian
    - name: Start service and enable Start on boot (Debian)
      service: name=apache2 state=started enabled=yes
      when: ansible_os_family == "Debian"
  
  - block: 

    - name: Install Apache on Alpine Linux
      apk: name=apache2 state=installed
      when: ansible_os_family == "Alpine"

    - name: Enable Apache Service
      service: name=apache2 state=started enabled=yes
      when: ansible_os_family == "Alpine"

  - name: Generate index.html file
    template: src={{ source_folder }}/index.j2 dest={{ destin_folder }}/index.html mode=0555
    notify: 
      - Restart Apache RedHat
      - Restart Apache Debian
      - Restart Apache Alpine

#  - name: Copy page to servers
#    copy: src={{ item }} dest={{ destin_folder }} mode=0555
#    with_fileglob: "{{ source_folder }}/*.*"  # Copy all files from source_folder
#    
#    notify:
#      - Restart Apache RedHat
#      - Restart Apache Debian

      


  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"
  
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"

  - name: Restart Apache Alpine
    service: name=apache2 state=restarted
    when: ansible_os_family == "Alpine"